@startuml

class Logger {
  - logger
  - logging
  + setup()
  + log_info(msg)
  + log_error(msg)
}

class DataHandler {
  - file_path
  - stream_id
  + get_data_maxwell()
  + save_to_zarr()
}

class Preprocessor {
  + preprocess()
  + get_channel_recording_stats()
}

class KilosortHandler {
  + run_kilosort()
  + get_kilosort_result()
}

class WaveformHandler {
  + extract_waveforms()
  + get_waveforms_result()
}

class QualityMetrics {
  + get_quality_metrics()
  + remove_violated_units()
}

class TemplateHandler {
  + get_template_metrics()
  + get_temp_similarity_matrix()
  + merge_similar_templates()
  + remove_similar_templates()
}

class ChannelAnalyzer {
  + get_unique_templates_channels()
  + get_channel_locations_mapping()
}

class Visualization {
  + plot_waveforms()
}

class Utilities {
  + find_connected_components()
}

class Helper {
  + isexists_folder_not_empty()
  + empty_directory()
}

class Main {
  + main()
  + process_block(file_path, time_in_s=300, stream_id='well000', recnumber=0, sorting_folder=f"{BASE_FILE_PATH}/Sorting_Intermediate_files", clear_temp_files=True)
  + routine_sequential(file_path, number_of_configurations, time_in_s)
  + routine_parallel(file_path, number_of_configurations, time_in_s)
}

Main --> Logger
Main --> DataHandler
Main --> Preprocessor
Preprocessor --> KilosortHandler
KilosortHandler --> WaveformHandler
WaveformHandler --> QualityMetrics
WaveformHandler --> TemplateHandler
TemplateHandler --> ChannelAnalyzer
WaveformHandler --> ChannelAnalyzer

@enduml
